/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Header from '../components/Header';
import NoteCard from '../components/NoteCard';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Anoted</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="p-4 grid gap-4 grid-cols-auto-fill items-center">
        <NoteCard />
        <NoteCard />
        <NoteCard />
      </main>
    </div>
  );
}
