/* eslint-disable @next/next/no-img-element */
import { createServerSupabaseClient } from '@supabase/auth-helpers-nextjs';
import Head from 'next/head';

import NoteCard from '../components/NoteCard';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Anoted</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4 grid gap-4 grid-cols-auto-fill items-center">
        {/* {notes.map((note) => (
          <NoteCard key={note.id} title={note.title} body={note.body} />
        ))} */}
      </main>
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  // Create authenticated Supabase Client
  const supabase = createServerSupabaseClient(ctx);
  // Check if we have a session
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session)
    return {
      redirect: {
        destination: '/auth/login',
        permanent: false,
      },
    };

  return {
    props: {
      user: session.user,
    },
  };
};
